"""语言表和按语言覆盖的提示词，取自沉浸式翻译 1.33.3（content_main.js / default_config.json），由脚本生成。"""

# (代码, 英文名, 本地名)，顺序与插件下拉框一致
LANGUAGES = [
    ('auto', 'Auto Detect', 'Auto Detect'),
    ('zh-CN', 'Simplified Chinese', '简体中文'),
    ('zh-TW', 'Traditional Chinese (Taiwan)', '繁體中文-台湾'),
    ('zh-HK', 'Traditional Chinese (Hong Kong)', '繁體中文-香港'),
    ('en', 'English', 'English'),
    ('ja', 'Japanese', '日本語'),
    ('ko', 'Korean', '한국어'),
    ('es', 'Spanish', 'Español'),
    ('de', 'German', 'Deutsch'),
    ('fr', 'French', 'Français'),
    ('pt', 'Portuguese', 'Português'),
    ('pt-br', 'Portuguese (Brazil)', 'Português (Brasil)'),
    ('ru', 'Russian', 'Русский'),
    ('yue', 'Cantonese (Traditional)', '粵語'),
    ('ar', 'Arabic', 'العربية'),
    ('it', 'Italian', 'Italiano'),
    ('ms', 'Malay', 'Bahasa Melayu'),
    ('id', 'Indonesian', 'Bahasa Indonesia'),
    ('vi', 'Vietnamese', 'Tiếng Việt'),
    ('af', 'Afrikaans', 'Afrikaans'),
    ('th', 'Thai', 'ไทย'),
    ('ur', 'Urdu', 'اردو'),
    ('zh-CN-NE', 'Northeastern Chinese', '東北官話'),
    ('bo', 'Tibetan', 'བོད་ཡིག'),
    ('wyw', 'Classical Chinese', '文言文'),
    ('am', 'Amharic', 'አማርኛ'),
    ('az', 'Azerbaijani', 'Azərbaycanca'),
    ('be', 'Belarusian', 'Беларуская'),
    ('ber-Latn', 'Tamazight', 'Tamazight'),
    ('ber-Tfng', 'Tamazight (Tifinagh)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ'),
    ('bg', 'Bulgarian', 'Български'),
    ('bn', 'Bengali', 'বাংলা'),
    ('bs', 'Bosnian', 'Bosanski'),
    ('ca', 'Catalan', 'Català'),
    ('ceb', 'Cebuano', 'Binisaya'),
    ('co', 'Corsican', 'Corsu'),
    ('cs', 'Czech', 'Čeština'),
    ('cy', 'Welsh', 'Cymraeg'),
    ('da', 'Danish', 'Dansk'),
    ('nl', 'Dutch', 'Nederlands'),
    ('el', 'Greek', 'Ελληνικά'),
    ('eo', 'Esperanto', 'Esperanto'),
    ('et', 'Estonian', 'Eesti'),
    ('eu', 'Basque', 'Euskara'),
    ('fa', 'Persian', 'فارسی'),
    ('fi', 'Finnish', 'Suomi'),
    ('fil', 'Filipino', 'Filipino'),
    ('fj', 'Fijian', 'Na Vosa Vakaviti'),
    ('fy', 'Frisian', 'Frysk'),
    ('ga', 'Irish', 'Gaeilge'),
    ('gd', 'Scottish Gaelic', 'Gàidhlig'),
    ('gl', 'Galician', 'Galego'),
    ('gu', 'Gujarati', 'ગુજરાતી'),
    ('ha', 'Hausa', 'Hausa'),
    ('haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi'),
    ('he', 'Hebrew', 'עברית'),
    ('hi', 'Hindi', 'हिन्दी'),
    ('hmn', 'Hmong', 'Hmoob'),
    ('hr', 'Croatian', 'Hrvatski'),
    ('ht', 'Haitian Creole', 'Kreyòl Ayisyen'),
    ('hu', 'Hungarian', 'Magyar'),
    ('hy', 'Armenian', 'Հայերեն'),
    ('ig', 'Igbo', 'Asụsụ Igbo'),
    ('is', 'Icelandic', 'Íslenska'),
    ('jw', 'Javanese', 'Basa Jawa'),
    ('ka', 'Georgian', 'ქართული'),
    ('kk', 'Kazakh', 'Қазақ Тілі'),
    ('km', 'Khmer', 'ភាសាខ្មែរ'),
    ('kn', 'Kannada', 'ಕನ್ನಡ'),
    ('ku', 'Kurdish (Kurmanji)', 'Kurmancî'),
    ('ckb', 'Kurdish (Sorani)', 'کوردیی سۆرانی'),
    ('ky', 'Kyrgyz', 'Кыргызча'),
    ('la', 'Latin', 'Latina'),
    ('lb', 'Luxembourgish', 'Lëtzebuergesch'),
    ('lo', 'Lao', 'ລາວ'),
    ('lt', 'Lithuanian', 'Lietuvių'),
    ('lv', 'Latvian', 'Latviešu'),
    ('mg', 'Malagasy', 'Malagasy'),
    ('mi', 'Maori', 'Māori'),
    ('mk', 'Macedonian', 'Македонски'),
    ('ml', 'Malayalam', 'മലയാളം'),
    ('mn', 'Mongolian (Cyrillic)', 'Монгол (Кирилл)'),
    ('mn-Mong', 'Mongolian (Traditional Script)', 'ᠮᠣᠩᠭᠣᠯ'),
    ('mr', 'Marathi', 'मराठी'),
    ('mt', 'Maltese', 'Malti'),
    ('mww', 'Hmong Daw', 'Hmong Daw'),
    ('my', 'Burmese', 'မြန်မာစာ'),
    ('ne', 'Nepali', 'नेपाली'),
    ('no', 'Norwegian', 'Norsk'),
    ('ny', 'Chichewa', 'Chichewa'),
    ('otq', 'Querétaro Otomi', 'Hñähñu'),
    ('pa', 'Punjabi', 'ਪੰਜਾਬੀ'),
    ('pl', 'Polish', 'Polski'),
    ('ps', 'Pashto', 'پښتو'),
    ('ro', 'Romanian', 'Română'),
    ('sa', 'Sanskrit', 'संस्कृतम्'),
    ('sd', 'Sindhi', 'سنڌي'),
    ('si', 'Sinhala', 'සිංහල'),
    ('sk', 'Slovak', 'Slovenčina'),
    ('sl', 'Slovenian', 'Slovenščina'),
    ('sm', 'Samoan', 'Gagana Samoa'),
    ('sn', 'Shona', 'ChiShona'),
    ('so', 'Somali', 'Soomaali'),
    ('sq', 'Albanian', 'Shqip'),
    ('sr', 'Serbian', 'Српски'),
    ('sr-Cyrl', 'Serbian (Cyrillic)', 'Српски (Ћирилица)'),
    ('sr-Latn', 'Serbian (Latin)', 'Srpski (Latinica)'),
    ('st', 'Sesotho', 'Sesotho'),
    ('su', 'Sundanese', 'Basa Sunda'),
    ('sv', 'Swedish', 'Svenska'),
    ('sw', 'Swahili', 'Kiswahili'),
    ('ta', 'Tamil', 'தமிழ்'),
    ('te', 'Telugu', 'తెలుగు'),
    ('tg', 'Tajik', 'Тоҷикӣ'),
    ('tlh', 'Klingon', 'tlhIngan Hol'),
    ('tlh-Qaak', 'Klingon (piqaD)', 'tlhIngan Hol (pIqaD)'),
    ('to', 'Tongan', 'lea fakatonga'),
    ('tr', 'Turkish', 'Türkçe'),
    ('ty', 'Tahitian', 'Reo Tahiti'),
    ('ug', 'Uyghur', 'ئۇيغۇرچە'),
    ('uk', 'Ukrainian', 'Українська'),
    ('uz', 'Uzbek', 'Oʻzbek'),
    ('xh', 'Xhosa', 'isiXhosa'),
    ('yi', 'Yiddish', 'ייִדיש'),
    ('yo', 'Yoruba', 'Èdè Yorùbá'),
    ('yua', 'Yucatec Maya', "Màaya T'àan"),
    ('zu', 'Zulu', 'isiZulu'),
    ('ur-roman', 'Roman Urdu', 'Roman Urdu'),
]

# 插件 Google 翻译的语言代码映射里和自身不同的部分；不在 Google 列表里的语言不能用 Google 翻译
GOOGLE_CODES = {"af": "af", "am": "am", "ar": "ar", "auto": "auto", "az": "az", "be": "be", "ber-Latn": "ber-Latn", "ber-Tfng": "ber-Tfng", "bg": "bg", "bn": "bn", "bs": "bs", "ca": "ca", "ceb": "ceb", "ckb": "ckb", "co": "co", "cs": "cs", "cy": "cy", "da": "da", "de": "de", "el": "el", "en": "en", "eo": "eo", "es": "es", "et": "et", "eu": "eu", "fa": "fa", "fi": "fi", "fil": "tl", "fr": "fr", "fy": "fy", "ga": "ga", "gd": "gd", "gl": "gl", "gu": "gu", "ha": "ha", "haw": "haw", "he": "he", "hi": "hi", "hmn": "hmn", "hr": "hr", "ht": "ht", "hu": "hu", "hy": "hy", "id": "id", "ig": "ig", "is": "is", "it": "it", "ja": "ja", "jw": "jw", "ka": "ka", "kk": "kk", "km": "km", "kn": "kn", "ko": "ko", "ku": "ku", "ky": "ky", "la": "la", "lb": "lb", "lo": "lo", "lt": "lt", "lv": "lv", "mg": "mg", "mi": "mi", "mk": "mk", "ml": "ml", "mn": "mn", "mr": "mr", "ms": "ms", "mt": "mt", "my": "my", "ne": "ne", "nl": "nl", "no": "no", "ny": "ny", "pa": "pa", "pl": "pl", "ps": "ps", "pt": "pt-PT", "pt-br": "pt", "ro": "ro", "ru": "ru", "sa": "sa", "sd": "sd", "si": "si", "sk": "sk", "sl": "sl", "sm": "sm", "sn": "sn", "so": "so", "sq": "sq", "sr": "sr", "st": "st", "su": "su", "sv": "sv", "sw": "sw", "ta": "ta", "te": "te", "tg": "tg", "th": "th", "tr": "tr", "ug": "ug", "uk": "uk", "ur": "ur", "uz": "uz", "vi": "vi", "xh": "xh", "yi": "yi", "yo": "yo", "yue": "yue", "zh-CN": "zh-CN", "zh-HK": "zh-TW", "zh-TW": "zh-TW", "zu": "zu"}

RTL_LANGUAGES = ["ar", "arc", "az", "dv", "he", "ckb", "fa", "ur", "ug"]

# 插件 langOverrides：id 是 "<from>2<to>"，extends 表示先继承另一项
LANG_OVERRIDES = [
    {"id": "auto2zh-CN", "system": "你是专业的简体中文母语译者。请将每个 source item 分别准确、流畅地翻译为简体中文，保持原意、语气、段落、换行和格式；每一项只提供译文内容，不添加解释、前言或注释。若内容包含 HTML 标签，请根据译文语序正确放置并完整保留标签；完整保留 placeholder 和代码，专有名词及其他内容仅在无需翻译时保留。结合以下标题、摘要和术语上下文完成翻译：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "翻译为简体中文：\n\n{{text}}"},
    {"id": "auto2zh-TW", "system": "你是專業的臺灣繁體中文母語譯者。請將每個 source item 分別準確、流暢地翻譯為臺灣地區使用的繁體中文，保持原意、語氣、段落、換行與格式；每一項只提供譯文內容，不添加解釋、前言或註釋。若內容包含 HTML 標籤，請依譯文語序正確放置並完整保留標籤；完整保留 placeholder 與程式碼，專有名詞及其他內容僅在無需翻譯時保留。結合以下標題、摘要與術語脈絡完成翻譯：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "翻譯為臺灣地區繁體中文：\n\n{{text}}"},
    {"id": "auto2en", "system": "You are a professional native English translator. Translate each source item separately into accurate, fluent, natural English while preserving its meaning, tone, paragraphs, line breaks, and formatting. For each item, provide its translation without explanations, prefaces, or annotations. If the content contains HTML tags, retain every tag and place it correctly for the translated word order. Preserve placeholders and code; preserve proper nouns and other content only when they do not require translation. Use the following title, summary, and terminology context:{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "Translate to English:\n\n{{text}}"},
    {"id": "auto2ja", "system": "あなたはプロの日本語ネイティブ翻訳者です。各 source item をそれぞれ正確で流暢かつ自然な日本語に翻訳し、原文の意味、語調、段落、改行、書式を維持してください。各項目には翻訳文だけを記載し、説明、前置き、注釈を加えないでください。HTML タグが含まれる場合は、すべてのタグを保持し、日本語の語順に合う正しい位置に配置してください。placeholder とコードはそのまま保持し、固有名詞などの内容は翻訳不要な場合にのみ保持してください。次のタイトル、要約、用語の文脈を踏まえて翻訳してください：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "日本語に翻訳してください：\n\n{{text}}"},
    {"id": "auto2ko", "system": "당신은 전문 한국어 원어민 번역가입니다. 각 source item을 각각 정확하고 유창하며 자연스러운 한국어로 번역하고 원문의 의미, 어조, 문단, 줄바꿈, 형식을 유지하세요. 각 항목에는 번역문만 제공하고 설명, 서문 또는 주석을 추가하지 마세요. HTML 태그가 포함되어 있다면 모든 태그를 보존하고 번역문의 어순에 맞는 올바른 위치에 배치하세요. placeholder와 코드는 그대로 보존하고, 고유명사와 기타 내용은 번역할 필요가 없을 때만 보존하세요. 다음 제목, 요약 및 용어 문맥을 반영해 번역하세요:{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "한국어로 번역하세요:\n\n{{text}}"},
    {"id": "auto2ru", "system": "Вы профессиональный переводчик — носитель русского языка. Переведите каждый source item отдельно на точный, свободный и естественный русский язык, сохраняя смысл, тон, абзацы, переносы строк и форматирование оригинала. Для каждого элемента приводите только его перевод, без объяснений, предисловий и примечаний. Если текст содержит HTML-теги, сохраните все теги и разместите их в соответствии с порядком слов в переводе. Сохраняйте без изменений placeholder и код; имена собственные и другой контент сохраняйте только тогда, когда они не требуют перевода. Учитывайте следующий контекст заголовка, краткого содержания и терминов:{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "Переведите на русский язык:\n\n{{text}}"},
    {"id": "auto2fr", "system": "Vous êtes un traducteur professionnel de langue maternelle française. Traduisez séparément chaque source item dans un français fidèle, fluide et naturel, en conservant le sens, le ton, les paragraphes, les retours à la ligne et la mise en forme du texte original. Pour chaque élément, fournissez uniquement sa traduction, sans explication, préambule ni annotation. Si le contenu comporte des balises HTML, conservez-les toutes et placez-les correctement selon l'ordre des mots de la traduction. Conservez les placeholder et le code ; ne conservez les noms propres et les autres contenus que lorsqu'ils ne nécessitent pas de traduction. Tenez compte du contexte de titre, de résumé et de terminologie suivant :{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "Traduisez en français :\n\n{{text}}"},
    {"id": "auto2es", "system": "Eres un traductor profesional nativo de español. Traduce cada source item por separado a un español fiel, fluido y natural, conservando el significado, el tono, los párrafos, saltos de línea y el formato del original. Para cada elemento, proporciona únicamente su traducción, sin explicaciones, preámbulos ni anotaciones. Si el contenido incluye etiquetas HTML, consérvalas todas y colócalas correctamente según el orden de palabras de la traducción. Conserva los placeholder y el código; conserva los nombres propios y otros contenidos solo cuando no requieran traducción. Ten en cuenta el siguiente contexto de título, resumen y terminología:{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "Traduce al español:\n\n{{text}}"},
    {"id": "auto2pt", "system": "Você é um tradutor profissional nativo de português. Traduza cada source item separadamente para um português fiel, fluente e natural, preservando o significado, o tom, os parágrafos, as quebras de linha e a formatação do original. Para cada item, forneça somente a tradução correspondente, sem explicações, prefácios ou anotações. Se o conteúdo incluir tags HTML, preserve todas elas e posicione-as corretamente de acordo com a ordem das palavras na tradução. Preserve os placeholder e o código; preserve nomes próprios e outros conteúdos somente quando não precisarem de tradução. Considere o seguinte contexto de título, resumo e terminologia:{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "Traduza para português:\n\n{{text}}"},
    {"id": "auto2zh-CN-NE", "extends": "auto2zh-CN", "system": "你是专业的东北话翻译。请将每个 source item 分别准确地翻译成贴近生活的东北人口吻，在不改变原意与语气的前提下使用自然的东北方言、口头语和独特表达，并可适度体现夸张和幽默；每一项只提供译文内容，不添加解释、前言或注释。保持原文的段落、换行和格式；若内容包含 HTML 标签，请根据译文语序正确放置并完整保留标签；完整保留 placeholder 和代码，专有名词及其他内容仅在无需翻译时保留。结合以下标题、摘要和术语上下文完成翻译：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "用东北人的口吻翻译：\n\n{{text}}"},
    {"id": "wyw2zh-CN", "system": "你是精通古文的学者。请将每个 source item 分别准确、流畅地翻译为现代白话文，准确传达原文含义、语气、典故和文化内涵，保留原文意境与精神，并使用现代人易于理解的表达；每一项只提供白话文译文，不添加解释、前言或注释。保持原文的段落、换行和格式；若内容包含 HTML 标签或特殊标记，请根据译文语序正确放置并完整保留；完整保留 placeholder 和代码，专有名词、人名和地名使用现代通用称呼，其他无需翻译的内容保持原样。结合以下标题、摘要和术语上下文完成翻译：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "将古文翻译为现代白话文：\n\n{{text}}"},
    {"id": "auto2wyw", "system": "你是专业的文言文译者。请将每个 source item 分别准确地译为贴近古风的文言文，在不改变原意与语气的前提下使用古雅的虚词、句式和词汇，依语境选择恰当文体，注重意境与韵律；现代概念尽量采用恰当的典故或文言表达。每一项只提供文言文译文，不添加解释、前言或注释。保持原文的段落、换行和格式；若内容包含 HTML 标签或特殊标记，请根据译文语序正确放置并完整保留；完整保留 placeholder 和代码，专有名词及其他内容仅在无需翻译时保留。结合以下标题、摘要和术语上下文完成翻译：{{title_prompt}}{{summary_prompt}}{{terms_prompt}}\n\n{{imt_style_guide}}", "user": "将现代文翻译为文言文：\n\n{{text}}"},
]
